### ISSUE TITLE
Home - our people - photo size

### ISSUE THREAD

**Issue by acosby** [ChemistryPittsburgh/wordpress-test#2]
Desktop browser, tablet view. The employee profile doesn't match the PSDs. Photo should be smaller and to the left of the text, instead of vertically stacked. It displays correctly on an actual tablet.

how it is currently:
![screen shot 2015-05-15 at 1 21 23 pm](https://cloud.githubusercontent.com/assets/12141357/7658089/4833d7fc-fb05-11e4-882b-afcfe989ef0c.png)

how it is in PSDs:
![screen shot 2015-05-15 at 1 22 22 pm](https://cloud.githubusercontent.com/assets/12141357/7658103/6b2200f4-fb05-11e4-9af5-ead2d9e7c048.png)

**Comment by cjezowicz** [comment]
Adjusted the CSS breakpoints to better reflect the PSDs. I added % margins at 725px and enacted mobile around 500px
