### ISSUE TITLE
Navigation - Add dropdowns to "Industries" and "Services" on Desktop and Tablet View.

### ISSUE THREAD

**Issue by jaronoff** [ChemistryPittsburgh/wordpress-test#36]
Add dropdowns to "Industries" and "Services" on the desktop and tablet views. For mobile, omit the dropdown navigation, as its too much to display on screen. The fallback in that instance is the breadcrumb navigation and overview pages.

**Comment by cjezowicz** [comment]
Dropdown created and implemented for all navigation items except for projects
