### ISSUE TITLE
home - spacing on mobile

### ISSUE THREAD

**Issue by acosby** [ChemistryPittsburgh/wordpress-test#4]
iphone 6

Lots of white space around the featured employee. PSDs show it a little tighter, can you adjust that?

Also the text in the green bar breaks at a weird spot ("Work" is the only word that gets pushed to the second line).

how it is now:
![img_5585](https://cloud.githubusercontent.com/assets/12141357/7658554/264a7f7a-fb09-11e4-9bce-e1b03deefdac.PNG)

compared to PSD:
![screen shot 2015-05-15 at 1 50 40 pm](https://cloud.githubusercontent.com/assets/12141357/7658579/6097960e-fb09-11e4-9f2d-1d14cefa879b.png)

**Comment by cjezowicz** [comment]
Fixed line height at mobile sizes and added a &nbsp; between the last two words
Adjusted spacing at 550px to look closer to the psds
