### ISSUE TITLE
Adjust height on the section headers on overview pages / introduce different colors to the sections.

### ISSUE THREAD

**Issue by jaronoff** [ChemistryPittsburgh/wordpress-test#40]
Client was somewhat reluctant at the vibrancy of the orange section on the careers page. feedback was to adjust the height of the section, as well as introduce some more calming colors, possibly pulling from their existing color palette.

**Comment by cjezowicz** [comment]
Added custom colors to the custom post types. These colors can be edited at the clients discretion from the admin section. I also adjusted the height of these sections.
