### ISSUE TITLE
Projects Page - Put services in one column instead of 3.

### ISSUE THREAD

**Issue by jaronoff** [ChemistryPittsburgh/wordpress-test#7]
Service Provided should be stacked into one column instead of 3.

![mozilla_firefox](https://cloud.githubusercontent.com/assets/433966/7658698/3a6e3df6-fb0a-11e4-8868-a2f6b9ddfa56.png)

**Comment by cjezowicz** [comment]
Adjusted CSS and breakpoints to allow different columns at different sizes.
