### ISSUE TITLE
Projects Page - Stack people section into one column, make div elements centered in container.

### ISSUE THREAD

**Issue by jaronoff** [ChemistryPittsburgh/wordpress-test#8]
Stack people section into one column, make div elements centered in container.

Screenshot shows PSD to the left (how it should be), page in Firefox at a mobile breakpoint to the right.

![mozilla_firefox_and_gai-mobile-projectpage_psd___66_7___ lorem_ipsum_dolor_sit_amet__consectetur_adipiscing_elit__phase__rgb_8_](https://cloud.githubusercontent.com/assets/433966/7658723/7d8da086-fb0a-11e4-9887-8ee5afb96b78.png)

**Comment by cjezowicz** [comment]
Adjust CSS to allow for centering at a certain width and to ensure proper text wrapping occurs
